### ISSUE TITLE
请问作者这个add back to top在哪里添加呢，thx

### ISSUE THREAD

**Issue by movesan** [BruceZhaoR/brucezhaor.github.io#2]

**Comment by BruceZhaoR** [comment]
@movesan 
页面布局: https://github.com/BruceZhaoR/brucezhaor.github.io/blob/master/_layouts/default.html#L108-L132 需要加载jQuery1.83以上  
参数说明：250 是只要页面超过了250就出现back-top图标，800 是从底部到顶部花费的时间。

对应的css： https://github.com/BruceZhaoR/brucezhaor.github.io/blob/master/assets/css/style-old.css#L837-L871

**Comment by BruceZhaoR** [comment]
这个博客是我手把手搭建起来的，当时没有任何前端基础，想到一个功能就直接去相应的地方改，而且是写死的那种，所以这个不适合当模板。

所以我最近考虑换一种方式搭建博客，[Hugo](https://github.com/spf13/hugo)。你可以了解一下，主题多，而且速度快。省去了jekyll的各种配置麻烦。虽然对于我们来说这些坑都跳过了，但是还是要对新技术保持好奇，跟上主流。

**Comment by movesan** [comment]
好的，谢了，最近也在弄博客，有点前端基础，但是自己是做后台开发的，所以呢还是要感谢这么详细的回答，总之加油哈，共同进步~

**Comment by BruceZhaoR** [comment]
@movesan  你挺厉害的啊，把我的搜索功能移植过去了。这个我琢磨了很长时间，还给lunr.js 作者提问了，只可惜这个不支持中文，所以尴尬了。建议标题或者描述里面加点英文关键词，这样方便搜索到。

国内你可以用多说的评论系统，这样方便大家互动留言之类的。

另外，可以不可以把我的博客地址加到你的友情链接里面去呢？ 😃  忘了说，加了搜索功能后，不能在博客中使用emoji了，要不然搜索会报错。。

**Comment by movesan** [comment]
@BruceZhaoR 
哈哈，其实我的博客就是在huangxuan的博客基础上参照你的一些功能实现的，在我的readme中也有写到，
关于搜索功能在网上也找了许多，也都不是很满意，但是感觉你这个还是比较好的，虽然只支持英文。

评论系统也考虑用多说着，但是感觉没有disqus美观，而且博客刚开不久，也算是暂时做个测试吧，慢慢会考虑换到多说的，disqus实在是不太适合国内环境啊。

友联木有问题，这就加上 : )

**Comment by BruceZhaoR** [comment]
@SIGAOYI 当然需要css啊。jQuery一般都在head里面引用了，不用单独复制过去了。你可以去movesan的博客看看他的commits，看看他是如何移植的。

**Comment by SIGAOYI** [comment]
@BruceZhaoR 好的，谢谢啦
我研究下

**Comment by movesan** [comment]
@BruceZhaoR 
最近考虑换到多说，可是这个duoshuo_username对应的是多说账号吗？而且根本找不到多说后台管理系统啊，我用我的账号访问http://movesan.duoshuo.com/admin/显示页面不存在，这个duoshuo_username应该怎么来呢？3q

**Comment by BruceZhaoR** [comment]
please see this PR https://github.com/cnfeat/cnfeat.github.io/pull/9
