### ISSUE TITLE
你好，作者每篇文章的阅读量是怎么添加的呢？

### ISSUE THREAD

**Issue by movesan** [BruceZhaoR/brucezhaor.github.io#3]
我的是在post.html里用js添加的，但是有些问题，想知道作者是采用什么方式统计的呢

**Comment by BruceZhaoR** [comment]
点击release，里面有说明。
在2017年02月14日 16:38，movesan 写道:

我的是在post.html里用js添加的，但是有些问题，想知道作者是采用什么方式统计的呢

**Comment by SIGAOYI** [comment]
最新一版的readme么？我也没找到文章阅读量统计的说明。
不好意思，非程序员，个人兴趣混github，有空的话，劳烦解答。

**Comment by movesan** [comment]
@SIGAOYI 
在release提交说明version 2.0中作者更新的版本中，具体设置方法可以查看这篇博客
http://jerryzou.com/posts/introduction-to-hit-kounter/
作者就是采用此方法实现的

**Comment by BruceZhaoR** [comment]
楼上正解。
https://github.com/BruceZhaoR/brucezhaor.github.io/releases/tag/v2.0

近期没有更新博客，是因为准备弃用 jekyll，采用Hugo。还在了解学习中。

**Comment by SIGAOYI** [comment]
@movesan 感谢已经搞定了！
@BruceZhaoR 
追问一个问题，其实应该放在[issues#2 add back to top](https://github.com/BruceZhaoR/brucezhaor.github.io/issues/2)
我copy了default.html_L108-L132的那段back-to-top的代码到我的default.html的文件中（我用的是HUX默认的那个default文件），并且也按引用地址将jQuery1.83的文件一起copy过来了。

但是在我的页面上木有生效，是否有其他地方要做联动调整的？
我猜测是不是CSS的问题？哪里要引用一下？
不是程序猿，问题可能很小白，见谅，感谢解答！
