### ISSUE TITLE
如何控制首页post内容预览的字数？

### ISSUE THREAD

**Issue by SIGAOYI** [BruceZhaoR/brucezhaor.github.io#4]
小的又来了~
如题，默认的预览太长了，想缩短一点

蟹蟹！

**Comment by BruceZhaoR** [comment]
@SIGAOYI  能不能上个链接或者截图。这个模板好久没有碰了，已经不是很熟悉了。

**Comment by SIGAOYI** [comment]
@BruceZhaoR 我已经自己研究出来了，哈哈，谢谢anyway
