### ISSUE TITLE
你好，大神，我又来了

### ISSUE THREAD

**Issue by SIGAOYI** [BruceZhaoR/brucezhaor.github.io#5]
你好
post 文章的行高、字号、间距等在哪里设置呢？

期待解答，感谢！

**Comment by BruceZhaoR** [comment]
@SIGAOYI  
全局： https://github.com/BruceZhaoR/brucezhaor.github.io/blob/master/assets/css/style-old.css#L49-L62

手机端响应调整：https://github.com/BruceZhaoR/brucezhaor.github.io/blob/master/assets/css/style-old.css#L886-L908

我用了压缩工具，把css的空白地方压缩了，所以不太好找，我自己备份了一个标准格式的old-css，用于调整，然后压缩替换

`@media`是根据显示界面的宽度不同进行的响应式调整。调整post的设置大概就是 `.post-container p `之类的地方，你自己查找一下吧。比如后面我调整了手机端的文章排版，稍微写了一点注释，你自己看看吧。

快大半年没有写博客了，主要还是太懒，我准备近期重构的。:fighting:

**Comment by SIGAOYI** [comment]
感谢感谢感谢
感动感动感动
！！！！！！
