### ISSUE TITLE
关于 paginator分页循环的问题

### ISSUE THREAD

**Issue by SIGAOYI** [BruceZhaoR/brucezhaor.github.io#7]
大神好！
我给原本是首页的“index.html”文件创建了一个新的路径："home/index.html"（新建了一个home文件夹）
后好像`{% for post in paginator.posts %}`就失效了，google上说在config文件里可以配置分页循环的路径，但是尝试了无效，求解。感谢！

ps:我是自制了一个landingpage，想做个入口，再点击跳转原先的首页。
<img width="1047" alt="paginator" src="https://user-images.githubusercontent.com/20675570/29027098-b678e21e-7bb1-11e7-9c18-b9ef6cca2e1a.png">

**Comment by BruceZhaoR** [comment]
https://stackoverflow.com/questions/21248607/jekyll-pagination-on-every-page

**Comment by SIGAOYI** [comment]
再次感谢！！
已解决;)
