### ISSUE TITLE
文章分类问题 Categories页的category标签乱码，打不开

### ISSUE THREAD

**Issue by qytang326** [BruceZhaoR/brucezhaor.github.io#8]
您好！我copy了您的categories页,应用到我的页面上，然而惊奇的发现，中文的category为乱码无法显示，导致整个页面都显示异常，不知道问题出在哪里，这里是出错的页面位置链接 [Categories](https://theme.quanyin.ml/categories/)，这里repo的位置 [gh-pages-theme](https://github.com/qytang326/gh-pages-theme)

**Comment by BruceZhaoR** [comment]
@qytang326  刚初步看了一下主要问题是:

1. 因为你用了中文作为url链接, 但是url只允许ASCII编码的字符，中文都要转码，所以你的中文`转载`被转码了。参考：<http://www.w3school.com.cn/html/html_urlencode.asp>

2. 另外我在`_config.yml` 中定义了 `categories_path` 
<https://github.com/BruceZhaoR/brucezhaor.github.io/blob/master/categories.html#L28>
<https://github.com/BruceZhaoR/brucezhaor.github.io/blob/master/_config.yml#L33>

**我的页面：**
![category-debug-1](https://user-images.githubusercontent.com/8092534/31333049-3fbdb3de-ad1b-11e7-83f1-0411e06d1680.png)

**你的页面：**
![category-debug](https://user-images.githubusercontent.com/8092534/31333042-3a77b7c6-ad1b-11e7-89f8-fc359267a8d9.png)


**修改意见：** 
你先在_config.yml里面加上 `categories_path:categories`，然后`jekyll server`本地预览看看行不行；

如果还是有问题，那你需要自定义一下标签，自己写一个js，具体可以参考：
<https://www.w3schools.com/bootstrap/bootstrap_ref_js_tab.asp>

**Comment by BruceZhaoR** [comment]
@qytang326 你的模板加了很多东西，我觉得很有意思，等我有时间重构博客的时候去借鉴一下，到时候可能需要向你咨询一下 😀

**Comment by qytang326** [comment]
页面显示不全是因为我把部分标签的位置放错了。。

>因为你用了中文作为url链接, 但是url只允许ASCII编码的字符，中文都要转码

我觉得这可能不是主要原因，问题或许在别处（当然这也是个问题之一），一个例子是catalog中的链接就是 ```#中文 ```，以及Hux博客的[tag页](http://huangxuan.me/tags)，依然在有中文的存在。

**Comment by BruceZhaoR** [comment]
@qytang326 刚看了你的页面，发现你的test是有用的 🤙 。你查看Hux博客的tag页的源代码，你会发现他的中文链接没有被转码，而你的被转掉了。 😞 

你说的 `#中文` 是一个锚，用于当前页面内的跳转。我的文章页面也有，因为加载了anchor.js, 例如<https://brucezhaor.github.io/blog/2016/01/07/Mathjax-with-jekyll/#写在前面的话>，其主要原因是我的中文没有转成 `%E8%BD%...`

**Comment by qytang326** [comment]
很好奇是怎么确定是不是要转码的。。。😞
暂时只能先这样了，之后有时间再找原因吧，感谢！

**Comment by BruceZhaoR** [comment]
@qytang326  你看这个： http://helenys.li/categories/#成长-ref   https://github.com/helenysli/helenysli.github.io

我估计是在开头加入了 `<html lang="zh-CN">`，而你的<...  lang="en">，所以出现了问题？

**Comment by qytang326** [comment]
试了下，并不行。莫名其妙，搞不懂...

**Comment by qytang326** [comment]
知道原因了，是因为插件jekyll-mentions的原因，禁用之后就好了。
